### ISSUE TITLE
Default template MSAL Login fails out of the box 

### ISSUE THREAD

**Issue by morning4coffe-dev** [unoplatform/uno.templates#209]
## Current behavior
When I create a new app from the Wizard with MSAL enabled and I enter my `clientId` I get this error:

`System.InvalidOperationException: Command 'Login' failed when executing command with '-null-'.
 ---> System.Exception: IDispatcher required to call LoginAsync on MSAL provider (Parameter 'dispatcher')
   at Uno.Extensions.Authentication.MSAL.MsalAuthenticationProvider.InternalLoginAsync(IDispatcher dispatcher, IDictionary2 credentials, CancellationToken cancellationToken)
   at Uno.Extensions.Authentication.BaseAuthenticationProvider.LoginAsync(IDispatcher dispatcher, IDictionary2 credentials, CancellationToken cancellationToken)
   at Uno.Extensions.Authentication.AuthenticationService.LoginAsync(IDispatcher dispatcher, IDictionary2 credentials, String provider, Nullable1 cancellationToken)
   at UnoApp3.Presentation.LoginModel.Login(CancellationToken token)
   at UnoApp3.Presentation.BindableLoginModel.<>c__DisplayClass1_0.<<-ctor>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Uno.Extensions.Reactive.Commands.AsyncCommand.SubCommand.<>c__DisplayClass7_0.<<TryExecute>b__0>d.MoveNext()
   --- End of inner exception stack trace ---`

## Expected behavior
Should not fail out of the box. 

## How to reproduce it (as minimally and precisely as possible)

1. Create new Uno project with Visual Studio
2. Select Default template
3. Customize it with adding MSAL auth
4. Enter your `clientId`

## Environment

Nuget Package: 

Package Version(s): 

Affected platform(s):

- All

**Comment by nickrandolph** [comment]
Hey sorry for the delay in responding to this - Can you try updating to the latest [Microsoft.Identity.Client](https://www.nuget.org/packages/Microsoft.Identity.Client) and let me know if this is still an issue

**Comment by morning4coffe-dev** [comment]
Nope, that doesn't seem to help. I created a new project with the latest version and updated the package to 4.56.0, but I can still repro this issue.

**Comment by nickrandolph** [comment]
ok, let me see if I can track down what's going on. Just to confirm, this isn't working for you on any platform? correct?

**Comment by nickrandolph** [comment]
Ok, looks like an issue with the template which the associated PR should fix. In meantime, if you make the same change to your application that's in [this commit](https://github.com/unoplatform/uno.templates/pull/273/commits/61bf3daea97de02ece13ab3797dc93e756117a0e), you should be good to go. Essentially Login is failing because it needs to run on UI thread but no dispatcher is being passed into the auth method
